version: '3.8'

services:
  db:
    container_name: db
    build:
      context: ./
      dockerfile: osm/Dockerfile
    environment:
      - POSTGRES_DB=moscow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=verySecret
    ports:
      - "5432:5432"
    networks:
      - app

networks:
  app: