version: '3.8'

services:
  db:
    container_name: db
    build:
      context: ./
      dockerfile: osm/Dockerfile
    environment:
      - POSTGRES_DB=moscow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=verySecret
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app

networks:
  app:

volumes:
  pg_data:


