version: '3.8'

services:
  db:
    container_name: db
    build:
      context: ./
      dockerfile: osm/Dockerfile
    environment:
      - POSTGRES_DB=moscow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=verySecret
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app
#  wiki:
#    container_name: wiki
#    build:
#      context: ./
#      dockerfile: wiki/Dockerfile
#    environment:
#      - MARIADB_ROOT_PASSWORD=verySecret
#    ports:
#      - "3306:3306"
#    volumes:
#      - wiki_data:/var/lib/mysql
#    networks:
#      - app

networks:
  app:

volumes:
  pg_data:
  wiki_data:
